# Generated by Django 3.0.8 on 2020-07-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Single Home', 'verbose_name_plural': 'Multiple Home page'},
        ),
    ]
